### ISSUE TITLE
Indeterminancy in server tests

### ISSUE THREAD

**Issue by devYaoYH** [googleinterns/scan-and-go#100]
`yarn test` - Success
`yarn test --detectOpenHandles` - Last test fails
Need to investigate further

**Comment by devYaoYH** [comment]
Side effect of detected open handles also preventing `jest` from exiting after tests are complete
- Delays completion of server testing script by ~1min

**Comment by devYaoYH** [comment]
Side-effect of #105, resolving that issue would resolve this one as well.

**Comment by redhoteggplant** [comment]
Just adding a note that open handles are separate and seem to be an [issue in supertest](https://github.com/visionmedia/supertest/issues/520), and current workarounds are just using `setTimeout()` or `--forceExit`

**Comment by redhoteggplant** [comment]
(Just adding more information in case we come back to this issue)

Running `jest test` gives the following warning:
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

Running `jest --detectOpenHandles` as suggested detects open handles from `app.listen()` or `request(app).get()`, with an example output below:
```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPSERVERWRAP

      38 | app.use(compression());
      39 | 
    > 40 | server = app.listen(PORT, function () {
         |              ^
      41 |   console.log(config.ENV);
      42 | });
      43 | 
```

Attempts:
1. `server.close()` at the end of all tests
2. `server.close()` in `afterAll()` 
3. Remove `app.listen()` and `server.close()` in test env, similar to [here](https://stackoverflow.com/questions/51968480/jest-detects-open-handle-with-express-app)
4. setting up an agent that uses the allocated port instead of a random port, or using `end()` to force supertest to close the automatic bound connection, as suggested in the [supertest issue #520](https://github.com/visionmedia/supertest/issues/520#issuecomment-436071071)
5. Add ` Promise.all(firebase.apps().map(app => app.delete()))`  to clean up Firebase apps after tests, as the docs [note](https://firebase.google.com/docs/rules/unit-tests#database) that that initialized apps with active listeners prevent JavaScript from exiting
6. Hacky ways: run jest with `--forceExit`, or `setTimeout()` after all tests
